version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python -m venv .venv
      - run: . .venv/bin/activate && pip install -r requirements.txt
      - run: . .venv/bin/activate && PYTHONPATH=. pytest -q
workflows:
  build_and_test:
    jobs:
      - build
